### ISSUE TITLE
some concern about the new version

### ISSUE THREAD

**Issue by brianping7** [rytilahti/python-mirobo#3]
Hi,

just saw the new version, why we try to get the device id and serial no every time? is it because it will change? i thought config it will be nice.  reduce the network traffic

**Comment by rytilahti** [comment]
It's because we don't know what's "device id" nor "serial" for real. To my understanding some people have their robots with the same "device id" as I do, meaning that it's possible to detect them nicely, but some others do not (different hardware/firmware?).

In order to make it easy for people to try the lib & script out it's easier to force a hello packet during the initial connection. This could be optimized to avoid sending the discovery and to reduce the network traffic, but currently I doubt it's worth it.

For users of the library part it's possible to just use the context manager to execute multiple commands without requiring separate discovery calls:
```
with Vacuum('123.123.123.123') as v:
    if v.status() == 12: # error
        v.home()  # return home
```

**Comment by brianping7** [comment]
sure, thanks for the explanation.  :)
